version: '3'
services:
  mysql:
    image: mysql:8.0.25
    container_name: baseContainer
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode="" --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: base
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: '1'
      LANG: C.UTF-8
    volumes:
      - .data/mysql:/var/lib/mysql
    ports:
      - 3322:3306
  app:
    build: .
    container_name: db-base
    ports:
      - 3000:8888
    volumes:
      - .:/app
    depends_on:
      - mysql

  redis:
    image: 'redis:6-alpine'
    container_name: base-redis
    ports:
      - 6380:6379
    volumes:
      - .data/redis:/data
