app:
  name: APP_NAME
  port: APP_PORT
  env: NODE_ENV
  isTest: IS_TEST

master:
  host: MYSQL_HOST
  port: MYSQL_PORT
  username: MYSQL_USERNAME
  password: MYSQL_PASSWORD
  database: MYSQL_DATABASE

report:
  host: MYSQL_HOST
  port: MYSQL_PORT
  username: MYSQL_USERNAME
  password: MYSQL_PASSWORD
  database: MYSQL_DATABASE

cron:
  enable:
    __name: CRON_ENABLE
    __format: json

redis:
  host: REDIS_HOST
  port: REDIS_PORT